// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_API_KEY_WEB'),
    appId: '1:335280092583:web:d250e88c2308c6966cf282',
    messagingSenderId: '335280092583',
    projectId: 'calorie-tracker-3921e',
    authDomain: 'calorie-tracker-3921e.firebaseapp.com',
    storageBucket: 'calorie-tracker-3921e.firebasestorage.app',
    measurementId: 'G-53QGLJHMK8',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_API_KEY_ANDROID'),
    appId: '1:335280092583:android:878ec989ac0b7cbc6cf282',
    messagingSenderId: '335280092583',
    projectId: 'calorie-tracker-3921e',
    storageBucket: 'calorie-tracker-3921e.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_API_KEY_IOS'),
    appId: '1:335280092583:ios:389d030408e512926cf282',
    messagingSenderId: '335280092583',
    projectId: 'calorie-tracker-3921e',
    storageBucket: 'calorie-tracker-3921e.firebasestorage.app',
    iosBundleId: 'com.example.calorieTrackerApp',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_API_KEY_IOS'),
    appId: '1:335280092583:ios:389d030408e512926cf282',
    messagingSenderId: '335280092583',
    projectId: 'calorie-tracker-3921e',
    storageBucket: 'calorie-tracker-3921e.firebasestorage.app',
    iosBundleId: 'com.example.calorieTrackerApp',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: dotenv.get('FIREBASE_API_KEY_WEB'),
    appId: '1:335280092583:web:03bc4bfa31fa71c46cf282',
    messagingSenderId: '335280092583',
    projectId: 'calorie-tracker-3921e',
    authDomain: 'calorie-tracker-3921e.firebaseapp.com',
    storageBucket: 'calorie-tracker-3921e.firebasestorage.app',
    measurementId: 'G-N9ESR418V7',
  );
}
