// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9vfVQCarv6-0UcLqHqjW4GY-QkqGhs5o',
    appId: '1:335280092583:web:d250e88c2308c6966cf282',
    messagingSenderId: '335280092583',
    projectId: 'calorie-tracker-3921e',
    authDomain: 'calorie-tracker-3921e.firebaseapp.com',
    storageBucket: 'calorie-tracker-3921e.firebasestorage.app',
    measurementId: 'G-53QGLJHMK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR1NoYJGCTYkUQ71GcbWEqvxtzSMIqvr8',
    appId: '1:335280092583:android:878ec989ac0b7cbc6cf282',
    messagingSenderId: '335280092583',
    projectId: 'calorie-tracker-3921e',
    storageBucket: 'calorie-tracker-3921e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ2yHn0iLCqfv2Z6-iAJxVjLJ7gIWPtJg',
    appId: '1:335280092583:ios:389d030408e512926cf282',
    messagingSenderId: '335280092583',
    projectId: 'calorie-tracker-3921e',
    storageBucket: 'calorie-tracker-3921e.firebasestorage.app',
    iosBundleId: 'com.example.calorieTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ2yHn0iLCqfv2Z6-iAJxVjLJ7gIWPtJg',
    appId: '1:335280092583:ios:389d030408e512926cf282',
    messagingSenderId: '335280092583',
    projectId: 'calorie-tracker-3921e',
    storageBucket: 'calorie-tracker-3921e.firebasestorage.app',
    iosBundleId: 'com.example.calorieTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9vfVQCarv6-0UcLqHqjW4GY-QkqGhs5o',
    appId: '1:335280092583:web:03bc4bfa31fa71c46cf282',
    messagingSenderId: '335280092583',
    projectId: 'calorie-tracker-3921e',
    authDomain: 'calorie-tracker-3921e.firebaseapp.com',
    storageBucket: 'calorie-tracker-3921e.firebasestorage.app',
    measurementId: 'G-N9ESR418V7',
  );
}
